### ISSUE TITLE
Add Navigation Links to navbar.js and index.html

### ISSUE THREAD

**Issue by SwayamBadhe** [mlscgescoe/E-Library#12]
## Description:
Our website is expanding, and we need to ensure seamless navigation between pages. Currently, our **navbar.js** script dynamically generates the navbar for pages in the "pages" folder. We also have a static navbar in the **index.html** file located outside the "pages" folder. Your task is to add relevant links to both the **navbar.js** script and the static navbar code in **index.html** to connect all the pages of the website.

## Task:

1. Open the **navbar.js** script located in the "js" folder.

2. Add navigation links to the script for each page in the "pages" folder. For example, if you have "about.html" and "contact.html" in the "pages" folder, add the corresponding links.

3. Open the **index.html** file located outside the "pages" folder.

4. In the static navbar code (usually found at the top of the **index.html** file), add links to each page in the "pages" folder using anchor tags (**<a>**).

5. Ensure that the links are correctly formatted and point to the respective HTML pages.

6. Test the links in both the dynamically generated navbar and the static navbar to make sure they navigate to the correct pages.

## Expected Outcome: 
The **navbar.js** script and the static navbar in **index.html** should contain working navigation links to connect all pages of the website.

## Getting Started:

1. Fork this repository.
2. Clone the forked repository to your local machine.
3. Create a new branch for this issue using the format: **feature/add-navigation-links.**
4. Implement the changes as described above in both **navbar.js** and **index.html.**
5. Push your changes to your forked repository.
6. Create a pull request to merge your changes into the main repository.

## Notes:

- Be sure to test all the links to ensure they work correctly.
- If you have any questions or need assistance, feel free to reach out.

This task will help improve the navigation experience on our website and is an important step in enhancing user engagement. Thank you for your contribution to our project!

**Comment by aalbak** [comment]
Assign me this issue

**Comment by SwayamBadhe** [comment]
> Assign me this issue

Thank you for your interest in contributing! In our collaborative environment, we often leave issues unassigned to encourage contributions from multiple contributors. Feel free to work on the issue and create a pull request when you're ready. I'll review it, and if everything looks good, we'll merge it. If you have any questions or need assistance while working on the issue, please don't hesitate to ask.

**Comment by SwayamBadhe** [comment]
Thank you for your interest in contributing! In our collaborative environment, we often leave issues unassigned to encourage contributions from multiple contributors. Feel free to work on the issue and create a pull request when you're ready. I'll review it, and if everything looks good, we'll merge it. If you have any questions or need assistance while working on the issue, please don't hesitate to ask.

Swayam
________________________________

**Comment by jMkwendy45** [comment]
i am interested in these issue if not assigned yet please assign to me
