### ISSUE TITLE
A good Readme for the Project

### ISSUE THREAD

**Issue by aryad14** [mlscgescoe/E-Library#14]

**Comment by Khushi-74** [comment]
hi @aryad14 I would like to work on this issue , would you please assign me under hacktoberfest 2023

**Comment by SwayamBadhe** [comment]
@Khushi-74 You have been assigned the issue!

**Comment by ISaumya1011** [comment]
Hi @aryad14,  I would like to work on this issue. Can you please assign me under hacktoberfest 2023

**Comment by Khushi-74** [comment]
> @Khushi-74 You have been assigned the issue!

HI @SwayamBadhe  I have updated the readme and raised a PR please review  also please add hacktoberfest accepted label

**Comment by SwayamBadhe** [comment]
@ISaumya1011 You can update and make changes in the current readme.md file and raise a PR

**Comment by ISaumya1011** [comment]
@SwayamBadhe Thank you so much for this opportunity. Will update and make changes to the readme.md file .

**Comment by ISaumya1011** [comment]
@SwayamBadhe Please check the changes. If any further changes need to be done, please let me know. N also, If you merge these changes, kindly accept my commits under hacktoberfest2023. Thank you!
